color: null
fieldLayouts:
  1478c7d1-63d8-4ed1-9c0c-6fde0fb38e91:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-30T19:55:48+00:00'
            elementCondition: null
            fieldUid: ae10a9d7-2e31-45bd-a334-d6fe39c19379 # Quote
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3870109d-bcf5-468b-bf32-9b3444260128
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-30T19:55:48+00:00'
            elementCondition: null
            fieldUid: f93a249c-cf72-4147-ac0d-64ed87954734 # Quote author
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cff4f30c-e08d-46b4-bd90-91653799eb9e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-30T19:55:48+00:00'
            elementCondition: null
            fieldUid: febc5ab2-f658-4720-a0e4-8497c27bebc2 # Quote source
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f97a3af-48f4-4dc2-b930-bf1828098c0a
            userCondition: null
            warning: null
            width: 100
        name: 'Block quote'
        uid: 1bea9714-583b-450b-9c0a-6a302eaea6d4
        userCondition: null
handle: blockquote
hasTitleField: false
icon: null
name: _Blockquote
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
