color: null
fieldLayouts:
  00cf15f5-dd00-4136-87c3-7cd3431d104f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-30T19:45:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7148d457-3cd7-4632-b531-890b7577054c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-30T19:50:50+00:00'
            elementCondition: null
            fieldUid: 0a0a61db-c42b-49a9-b6cd-9a96be13752e # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcaad72f-9360-483a-acdb-92c924ce95af
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e0f002d4-40fc-49a6-b10e-286d70d97d40
        userCondition: null
handle: cardsWithIcon
hasTitleField: true
icon: null
name: '_Cards with icon'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
