color: null
fieldLayouts:
  95ad267c-86f1-431f-ad6a-f6e2fad809b9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-29T16:55:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 27a6f6cc-46ff-44c4-ba8c-c7df81948da1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-29T19:50:36+00:00'
            elementCondition: null
            fieldUid: 0a0a61db-c42b-49a9-b6cd-9a96be13752e # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03e3ac3a-f16a-4196-b88f-c27d99518096
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-31T13:26:06+00:00'
            elementCondition: null
            fieldUid: 381ca719-b0cc-4bba-9b7d-4f65f18f781f # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 026b3318-a552-4d59-a31a-7bf72cf57483
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-29T19:29:51+00:00'
            elementCondition: null
            fieldUid: 02a30bda-d2b5-41f6-ba9b-8ce888e8e6ae # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1bda465-4194-445f-9da6-4676c9565ba6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-05T11:53:00+00:00'
            elementCondition: null
            fieldUid: 11c02d72-eede-4b3c-916a-cb8b112a6324 # Url Link text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0b9b073-8a19-47f8-9e36-9b1dcd9b37cc
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-01-03T14:15:11+00:00'
            elementCondition: null
            fieldUid: 274bbbf8-3795-475d-b50b-e2d36fc6cc20 # Url link
            handle: null
            includeInCards: false
            instructions: 'Use this for external links related to the content'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac09d79b-de34-4178-940d-e43cb153271c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-01-03T14:25:42+00:00'
            elementCondition: null
            heading: 'Quote or testimonial'
            type: craft\fieldlayoutelements\Heading
            uid: f9e2bb0d-8212-4008-aac3-a6f72a7fe775
            userCondition: null
          -
            dateAdded: '2025-01-03T14:15:11+00:00'
            elementCondition: null
            fieldUid: ae10a9d7-2e31-45bd-a334-d6fe39c19379 # Quote
            handle: null
            includeInCards: false
            instructions: 'Do not style'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5aadd562-77be-4510-8763-266d1a9a72da
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-03T14:15:11+00:00'
            elementCondition: null
            fieldUid: f93a249c-cf72-4147-ac0d-64ed87954734 # Quote author
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b90e869-0301-4395-b408-c2a10d46d668
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-03T14:15:11+00:00'
            elementCondition: null
            fieldUid: febc5ab2-f658-4720-a0e4-8497c27bebc2 # Quote source
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9463b131-1ba2-4e29-94a2-3e2e71afe8c8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-06T23:29:19+00:00'
            elementCondition: null
            fieldUid: 5ce4c45c-4533-4cba-8c45-36bfee218660 # Media embed
            handle: null
            includeInCards: false
            instructions: 'Replace embed video by clikcing add button then find embed button next to upload. Add your url here and save'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 804b6500-e858-4c60-9f25-49c5d0db00b1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-03T14:52:34+00:00'
            elementCondition: null
            fieldUid: 9a873930-78fb-428c-af5e-51a59e874862 # Embed
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 044027d2-33d6-47cc-acdb-b07a06f59a6e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 596055ab-1cec-46d3-814d-6061b3a7e3ef
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-29T19:50:36+00:00'
            elementCondition: null
            fieldUid: b9c4f964-3733-467b-b83e-e3802aa7b65f # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa0e4780-f411-48a2-878d-67409fa7d10c
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 3014834e-1879-4469-a996-4ee760462ecc
        userCondition: null
handle: caseStudy
hasTitleField: true
icon: null
name: 'Case study'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
