color: null
fieldLayouts:
  7387af0a-57d8-428c-9ae2-7356238b2087:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-02T16:13:55+00:00'
            elementCondition: null
            fieldUid: 381ca719-b0cc-4bba-9b7d-4f65f18f781f # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 798317bc-8751-4c0b-8eb5-f7c5c3af0327
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-02T16:13:55+00:00'
            elementCondition: null
            fieldUid: b2b15e5c-80c6-4bff-b6d1-e09b1bb48fac # Unsplash author
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1eccecd2-3b46-43dd-8013-4877c5081915
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-02T16:13:55+00:00'
            elementCondition: null
            fieldUid: 57a9f983-128e-4777-998d-57ad443ae51d # Unsplash url
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcf192ce-9df8-4721-a3d1-9edc65046812
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 367584ac-af59-4f6b-9d44-53afa3ded44d
        userCondition: null
handle: image
hasTitleField: false
icon: null
name: Image
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
