color: orange
fieldLayouts:
  27713ff2-9f5f-411c-8ec6-807d3bf50401:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-29T16:54:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e44b1d21-2c0a-44c5-bab4-7a4065c01754
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-29T19:50:17+00:00'
            elementCondition: null
            fieldUid: 0a0a61db-c42b-49a9-b6cd-9a96be13752e # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 364a8e2c-76f7-4e8b-966f-b13b198afa31
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-29T18:54:43+00:00'
            elementCondition: null
            fieldUid: 02a30bda-d2b5-41f6-ba9b-8ce888e8e6ae # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8021b457-a812-454c-a26a-b300c06e6414
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-30T12:38:09+00:00'
            elementCondition: null
            fieldUid: 7e35174b-e100-46d4-9d3b-c6127c0923ab # Content builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5de44a7-5710-4aff-a991-e6c6dc5eef35
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 39d3edd7-d35a-4485-8e08-3c5353005d89
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-29T19:50:17+00:00'
            elementCondition: null
            fieldUid: b9c4f964-3733-467b-b83e-e3802aa7b65f # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8199e5d-534f-47fa-8cf2-328d9836cde1
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: d5138a8a-e699-45ae-b447-e2a7c4b188a1
        userCondition: null
handle: page
hasTitleField: true
icon: null
name: page
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
