color: null
fieldLayouts:
  ac9dde13-9856-49d7-92ee-54894c1599f5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-07T14:42:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cfe2ed75-a241-44bd-80cb-a631e6f6f07e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-07T14:46:00+00:00'
            elementCondition: null
            fieldUid: 73707630-0f56-4ff8-a936-17113e86c682 # Organisation
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6ae9a34-cfd8-40c1-ab54-6057b151c862
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-07T14:46:00+00:00'
            elementCondition: null
            fieldUid: bc269089-f088-4dc3-85a3-8ca88015e753 # testimonial photo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37023a39-149b-406e-9312-8949027c1eab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-07T14:46:00+00:00'
            elementCondition: null
            fieldUid: ae10a9d7-2e31-45bd-a334-d6fe39c19379 # Quote
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2799cb3e-900f-4ed1-befd-b35c4671b1fd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-07T14:46:00+00:00'
            elementCondition: null
            fieldUid: 5ec282a8-339e-4230-83c8-3f37c13e0440 # LinkedIn profile link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b6e2a7e-2adf-40f2-a60d-6fea248863db
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6c76e38d-5e18-4428-8e7d-478f01858c00
        userCondition: null
handle: testimonial
hasTitleField: true
icon: null
name: Testimonial
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
