columnSuffix: null
handle: align
instructions: null
name: Align
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Default
        -
          - value
          - float-none
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Left '
        -
          - value
          - 'float-start pe-5 pb-5'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - 'float-end ps-5 pb-5'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
