columnSuffix: null
handle: align
instructions: null
name: Align
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - optgroup
          - Default
    -
      __assoc__:
        -
          - label
          - 'Left '
        -
          - value
          - float-start
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - float-end
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
