columnSuffix: null
handle: categoryDescription
instructions: null
name: 'Category description'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 3b9ecd0a-e61a-481d-8254-4787941102e7 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
