columnSuffix: null
handle: words
instructions: 'Add words separated by a comma no spaces to use on home page'
name: Words
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
