fieldLayouts:
  f2a91df4-7563-4095-bcb7-c8058e7aa350:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-03T20:24:22+00:00'
            elementCondition: null
            fieldUid: c6d65337-e203-4774-8ae2-435e731da46e # Slides
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64f22d84-4a24-408a-849c-0f402cd85796
            userCondition: null
            warning: null
            width: 100
        name: Slide
        uid: af9a7875-5628-4f4f-9967-0120256f103d
        userCondition: null
handle: orgSlider
name: 'Organisation slider'
sortOrder: 4
