defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7c06d5eb-a0c9-4660-b245-4a24e752b1a0 # Single page index
handle: blogIndex
maxAuthors: 1
name: 'Blog index'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  44796fd5-bb11-438e-893b-74cd6f43996f: # Rebecca Luff
    enabledByDefault: true
    hasUrls: true
    template: blog/index.twig
    uriFormat: blog
type: single
