defaultPlacement: end
enableVersioning: true
entryTypes:
  - e38830f8-1fcf-495a-b446-d72cfabe43c3 # Home
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  44796fd5-bb11-438e-893b-74cd6f43996f: # Rebecca Luff
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
