defaultPlacement: end
enableVersioning: true
entryTypes:
  - 1a2a8073-e10c-432b-841d-63f885e96036 # Menu
handle: menu
maxAuthors: 1
name: Menu
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  44796fd5-bb11-438e-893b-74cd6f43996f: # Rebecca Luff
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: ab94c5e8-1bf2-4e86-86f2-fb5dba7599bb
type: structure
