defaultPlacement: end
enableVersioning: true
entryTypes:
  - 27fa1076-49b0-4d82-97c2-9b92351cce5a # page
handle: mywork
maxAuthors: 1
name: Work
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  44796fd5-bb11-438e-893b-74cd6f43996f: # Rebecca Luff
    enabledByDefault: true
    hasUrls: true
    template: my-work
    uriFormat: my-work
type: single
