defaultPlacement: end
enableVersioning: true
entryTypes:
  - 19bdc5d9-798c-4b75-b12f-f3b309f06a0e # My work
handle: mywork
maxAuthors: 1
name: 'My Work'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  44796fd5-bb11-438e-893b-74cd6f43996f: # Rebecca Luff
    enabledByDefault: true
    hasUrls: true
    template: my-work
    uriFormat: my-work
type: single
