defaultPlacement: end
enableVersioning: true
entryTypes:
  - 27fa1076-49b0-4d82-97c2-9b92351cce5a # page
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  44796fd5-bb11-438e-893b-74cd6f43996f: # Rebecca Luff
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: 'pages/{slug}'
structure:
  maxLevels: null
  uid: e6e41f86-8e6e-4d21-8964-fd46bda78768
type: structure
